// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['main']['App']['AddCategory'](arg1);
}

export function AddTool(arg1, arg2) {
  return window['go']['main']['App']['AddTool'](arg1, arg2);
}

export function AutoAddScannedTools(arg1) {
  return window['go']['main']['App']['AutoAddScannedTools'](arg1);
}

export function BrowseDirectory(arg1) {
  return window['go']['main']['App']['BrowseDirectory'](arg1);
}

export function CleanInvalidPaths() {
  return window['go']['main']['App']['CleanInvalidPaths']();
}

export function CleanupDuplicateTools() {
  return window['go']['main']['App']['CleanupDuplicateTools']();
}

export function CleanupToolPaths() {
  return window['go']['main']['App']['CleanupToolPaths']();
}

export function DebugAllToolPaths() {
  return window['go']['main']['App']['DebugAllToolPaths']();
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteTool(arg1, arg2) {
  return window['go']['main']['App']['DeleteTool'](arg1, arg2);
}

export function DeleteToolNote(arg1, arg2) {
  return window['go']['main']['App']['DeleteToolNote'](arg1, arg2);
}

export function ExecuteCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2, arg3, arg4);
}

export function ExecuteCommandWithCustom(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ExecuteCommandWithCustom'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ExecuteCustomCommand(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExecuteCustomCommand'](arg1, arg2, arg3, arg4, arg5);
}

export function ExecuteToolCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteToolCommand'](arg1, arg2);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetFilePath(arg1) {
  return window['go']['main']['App']['GetFilePath'](arg1);
}

export function GetFileTypes() {
  return window['go']['main']['App']['GetFileTypes']();
}

export function GetJavaConfig() {
  return window['go']['main']['App']['GetJavaConfig']();
}

export function GetNewToolsFromScanned(arg1) {
  return window['go']['main']['App']['GetNewToolsFromScanned'](arg1);
}

export function GetToolAbsolutePath(arg1, arg2) {
  return window['go']['main']['App']['GetToolAbsolutePath'](arg1, arg2);
}

export function GetToolDirectory(arg1) {
  return window['go']['main']['App']['GetToolDirectory'](arg1);
}

export function GetToolNote(arg1, arg2) {
  return window['go']['main']['App']['GetToolNote'](arg1, arg2);
}

export function GetToolTypes() {
  return window['go']['main']['App']['GetToolTypes']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenGitHubPage() {
  return window['go']['main']['App']['OpenGitHubPage']();
}

export function OpenToolDirectory(arg1) {
  return window['go']['main']['App']['OpenToolDirectory'](arg1);
}

export function RepairConfigFile() {
  return window['go']['main']['App']['RepairConfigFile']();
}

export function SaveJavaConfig(arg1) {
  return window['go']['main']['App']['SaveJavaConfig'](arg1);
}

export function SaveToolNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveToolNote'](arg1, arg2, arg3);
}

export function ScanCustomDirectoryForTools(arg1) {
  return window['go']['main']['App']['ScanCustomDirectoryForTools'](arg1);
}

export function ScanResourcesForTools() {
  return window['go']['main']['App']['ScanResourcesForTools']();
}

export function ScanToolsInCustomPath(arg1) {
  return window['go']['main']['App']['ScanToolsInCustomPath'](arg1);
}

export function ScanToolsInPath(arg1) {
  return window['go']['main']['App']['ScanToolsInPath'](arg1);
}

export function SearchTools(arg1) {
  return window['go']['main']['App']['SearchTools'](arg1);
}

export function Select(arg1) {
  return window['go']['main']['App']['Select'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectJavaPath() {
  return window['go']['main']['App']['SelectJavaPath']();
}

export function UpdateCategoriesOrder(arg1) {
  return window['go']['main']['App']['UpdateCategoriesOrder'](arg1);
}

export function UpdateCategoryIcon(arg1, arg2) {
  return window['go']['main']['App']['UpdateCategoryIcon'](arg1, arg2);
}

export function UpdateCategoryName(arg1, arg2) {
  return window['go']['main']['App']['UpdateCategoryName'](arg1, arg2);
}

export function UpdateCategoryTools(arg1, arg2) {
  return window['go']['main']['App']['UpdateCategoryTools'](arg1, arg2);
}

export function UpdateTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTool'](arg1, arg2, arg3);
}

export function UpdateToolDescription(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateToolDescription'](arg1, arg2, arg3);
}
