// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCategory(arg1:string):Promise<void>;

export function AddTool(arg1:main.Tool,arg2:string):Promise<void>;

export function AutoAddScannedTools(arg1:Array<main.ScannedTool>):Promise<void>;

export function BrowseDirectory(arg1:string):Promise<Array<main.FileInfo>>;

export function CleanInvalidPaths():Promise<main.CleanupResult>;

export function CleanupDuplicateTools():Promise<void>;

export function CleanupToolPaths():Promise<void>;

export function DebugAllToolPaths():Promise<void>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeleteTool(arg1:string,arg2:string):Promise<void>;

export function DeleteToolNote(arg1:string,arg2:string):Promise<void>;

export function ExecuteCommand(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ExecuteCommandWithCustom(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function ExecuteCustomCommand(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ExecuteToolCommand(arg1:main.Tool,arg2:string):Promise<void>;

export function GetAllTags():Promise<Array<string>>;

export function GetCategories():Promise<main.Categories>;

export function GetFileInfo(arg1:string):Promise<Record<string, string>>;

export function GetFilePath(arg1:string):Promise<string>;

export function GetFileTypes():Promise<Array<Record<string, string>>>;

export function GetJavaConfig():Promise<main.JavaConfig>;

export function GetNewToolsFromScanned(arg1:Array<main.ScannedTool>):Promise<Array<main.ScannedTool>>;

export function GetToolAbsolutePath(arg1:string,arg2:string):Promise<string>;

export function GetToolDirectory(arg1:string):Promise<Array<main.FileInfo>>;

export function GetToolNote(arg1:string,arg2:string):Promise<string>;

export function GetToolTypes():Promise<Array<string>>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<Record<string, string>>;

export function OpenGitHubPage():Promise<void>;

export function OpenToolDirectory(arg1:string):Promise<void>;

export function RepairConfigFile():Promise<void>;

export function SaveJavaConfig(arg1:main.JavaConfig):Promise<void>;

export function SaveToolNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ScanCustomDirectoryForTools(arg1:string):Promise<Array<main.ScannedTool>>;

export function ScanResourcesForTools():Promise<Array<main.ScannedTool>>;

export function ScanToolsInCustomPath(arg1:string):Promise<Array<main.ScannedTool>>;

export function ScanToolsInPath(arg1:string):Promise<Array<main.ScannedTool>>;

export function SearchTools(arg1:string):Promise<Array<main.Tool>>;

export function Select(arg1:boolean):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectJavaPath():Promise<string>;

export function UpdateCategoriesOrder(arg1:Array<main.Category>):Promise<void>;

export function UpdateCategoryIcon(arg1:string,arg2:string):Promise<void>;

export function UpdateCategoryName(arg1:string,arg2:string):Promise<void>;

export function UpdateCategoryTools(arg1:string,arg2:Array<main.Tool>):Promise<void>;

export function UpdateTool(arg1:string,arg2:string,arg3:main.Tool):Promise<void>;

export function UpdateToolDescription(arg1:string,arg2:string,arg3:string):Promise<void>;
