// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTool(arg1, arg2) {
  return window['go']['main']['App']['AddTool'](arg1, arg2);
}

export function DeleteTool(arg1, arg2) {
  return window['go']['main']['App']['DeleteTool'](arg1, arg2);
}

export function ExecuteCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2, arg3, arg4);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetFilePath(arg1) {
  return window['go']['main']['App']['GetFilePath'](arg1);
}

export function GetToolTypes() {
  return window['go']['main']['App']['GetToolTypes']();
}

export function OpenToolDirectory(arg1) {
  return window['go']['main']['App']['OpenToolDirectory'](arg1);
}
