// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTool(arg1, arg2) {
  return window['go']['main']['App']['AddTool'](arg1, arg2);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteTool(arg1, arg2) {
  return window['go']['main']['App']['DeleteTool'](arg1, arg2);
}

export function ExecuteCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2, arg3, arg4);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetFilePath(arg1) {
  return window['go']['main']['App']['GetFilePath'](arg1);
}

export function GetToolTypes() {
  return window['go']['main']['App']['GetToolTypes']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenToolDirectory(arg1) {
  return window['go']['main']['App']['OpenToolDirectory'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function UpdateCategoryTools(arg1, arg2) {
  return window['go']['main']['App']['UpdateCategoryTools'](arg1, arg2);
}

export function UpdateTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTool'](arg1, arg2, arg3);
}

export function UpdateToolDescription(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateToolDescription'](arg1, arg2, arg3);
}
